version: '3'

volumes:
  local_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    env_file:
      - ./envs/web
    volumes:
      - ./:/app/:z
    ports:
      - "8501:8501"

  requirements:
    image: python:3.8-buster
    profiles:
      - utils
    volumes:
      - ./:/app/:z
