name: Deploy Dashboard App

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - develop

permissions:
  packages: write
  repository-projects: read
  id-token: write
  contents: read

jobs:
  push_dashboard_image:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}
      DOCKER_REPOSITORY: ghcr.io
      BASE_URL: https://dashboard-${{ github.ref_name }}.london.cloudapps.digital

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push dashboard image
        env:
          DOCKER_FILE: docker/web/Dockerfile
          DOCKER_IMAGE: dashboard

        run: |
          docker build . --file $DOCKER_FILE --tag $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --build-arg BASE_URL=$BASE_URL
          docker push -a $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE

  deploy_dashboard_image:
    needs: [push_dashboard_image]

    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.ref_name }}
      DOCKER_REPOSITORY: ghcr.io

    steps:
      - uses: actions/checkout@v3

      - name: Get space name
        uses: kanga333/variable-mapper@v0.2.2
        with:
          key: "${{github.ref_name}}"
          map: |
            {
              "sandbox": {"CF_SPACE": "sandbox"},
              "demo": {"CF_SPACE": "demo"},
              "temp": {"CF_SPACE": "temp"},
              "develop": {"CF_SPACE": "develop"},
              "staging": {"CF_SPACE": "staging"}
            }

      - name: Download CF CLI
        run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx

      - name: CF login
        run: ./cf login -a api.london.cloud.service.gov.uk -u "${{ secrets.CF_USER }}" -p "${{ secrets.CF_PASSWORD }}" -o co-i-ai -s "$CF_SPACE"

      - name: CF push dashboard app
        env:
          DOCKER_FILE: Dockerfile
          DOCKER_IMAGE: dashboard
          PAT_TOKEN_USER: ${{ secrets.PAT_TOKEN_USER }}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: CF_DOCKER_PASSWORD="$PAT_TOKEN" ./cf push dashboard-${{ github.ref_name }} --docker-image $DOCKER_REPOSITORY/${{ github.repository_owner }}/$DOCKER_IMAGE:$IMAGE_TAG --docker-username=$PAT_TOKEN_USER

      - uses: actions/checkout@v2
